# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corrfactor_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CorrFactorDialog(object):
    def setupUi(self, CorrFactorDialog):
        CorrFactorDialog.setObjectName("CorrFactorDialog")
        CorrFactorDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(CorrFactorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(CorrFactorDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.le_data_counts = QtWidgets.QLineEdit(self.groupBox)
        self.le_data_counts.setMaximumSize(QtCore.QSize(120, 16777215))
        self.le_data_counts.setObjectName("le_data_counts")
        self.gridLayout.addWidget(self.le_data_counts, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pb_calculate = QtWidgets.QPushButton(self.groupBox)
        self.pb_calculate.setObjectName("pb_calculate")
        self.gridLayout.addWidget(self.pb_calculate, 4, 1, 1, 1)
        self.le_data_time = QtWidgets.QLineEdit(self.groupBox)
        self.le_data_time.setMaximumSize(QtCore.QSize(120, 16777215))
        self.le_data_time.setObjectName("le_data_time")
        self.gridLayout.addWidget(self.le_data_time, 0, 1, 1, 1)
        self.le_bkg_time = QtWidgets.QLineEdit(self.groupBox)
        self.le_bkg_time.setMaximumSize(QtCore.QSize(120, 16777215))
        self.le_bkg_time.setObjectName("le_bkg_time")
        self.gridLayout.addWidget(self.le_bkg_time, 2, 1, 1, 1)
        self.le_bkg_counts = QtWidgets.QLineEdit(self.groupBox)
        self.le_bkg_counts.setMaximumSize(QtCore.QSize(120, 16777215))
        self.le_bkg_counts.setObjectName("le_bkg_counts")
        self.gridLayout.addWidget(self.le_bkg_counts, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(CorrFactorDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.le_factor = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_factor.setMaximumSize(QtCore.QSize(120, 16777215))
        self.le_factor.setObjectName("le_factor")
        self.gridLayout_2.addWidget(self.le_factor, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(CorrFactorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CorrFactorDialog)
        self.buttonBox.accepted.connect(CorrFactorDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CorrFactorDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CorrFactorDialog)

    def retranslateUi(self, CorrFactorDialog):
        _translate = QtCore.QCoreApplication.translate
        CorrFactorDialog.setWindowTitle(_translate("CorrFactorDialog", "Dialog"))
        self.groupBox.setTitle(_translate("CorrFactorDialog", "Calculator"))
        self.label.setText(_translate("CorrFactorDialog", "Data Measurement Time (s)"))
        self.label_3.setText(_translate("CorrFactorDialog", "Bkg Measurement Time (s)"))
        self.le_data_counts.setText(_translate("CorrFactorDialog", "1000000"))
        self.label_2.setText(_translate("CorrFactorDialog", "Data Measurement Counts"))
        self.pb_calculate.setText(_translate("CorrFactorDialog", "Do the math!"))
        self.le_data_time.setText(_translate("CorrFactorDialog", "3600"))
        self.le_bkg_time.setText(_translate("CorrFactorDialog", "3600"))
        self.le_bkg_counts.setText(_translate("CorrFactorDialog", "100000"))
        self.label_4.setText(_translate("CorrFactorDialog", "Bkg Measurement Counts"))
        self.groupBox_2.setTitle(_translate("CorrFactorDialog", "Set"))
        self.label_5.setText(_translate("CorrFactorDialog", "Correction Factor ( F >= 1.0)"))
        self.le_factor.setText(_translate("CorrFactorDialog", "1.0"))
