# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bkgtools_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BkgToolsWidget(object):
    def setupUi(self, BkgToolsWidget):
        BkgToolsWidget.setObjectName("BkgToolsWidget")
        BkgToolsWidget.resize(322, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(BkgToolsWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(BkgToolsWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.le_correction_factor = QtWidgets.QLineEdit(self.groupBox)
        self.le_correction_factor.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_correction_factor.setReadOnly(True)
        self.le_correction_factor.setObjectName("le_correction_factor")
        self.gridLayout.addWidget(self.le_correction_factor, 1, 0, 1, 1)
        self.pb_set_factor = QtWidgets.QPushButton(self.groupBox)
        self.pb_set_factor.setObjectName("pb_set_factor")
        self.gridLayout.addWidget(self.pb_set_factor, 1, 1, 1, 1)
        self.pb_set_sigma = QtWidgets.QPushButton(self.groupBox)
        self.pb_set_sigma.setObjectName("pb_set_sigma")
        self.gridLayout.addWidget(self.pb_set_sigma, 2, 1, 1, 1)
        self.le_gauss_sigma = QtWidgets.QLineEdit(self.groupBox)
        self.le_gauss_sigma.setMaximumSize(QtCore.QSize(60, 16777215))
        self.le_gauss_sigma.setReadOnly(True)
        self.le_gauss_sigma.setObjectName("le_gauss_sigma")
        self.gridLayout.addWidget(self.le_gauss_sigma, 2, 0, 1, 1)
        self.bp_view_background = QtWidgets.QPushButton(self.groupBox)
        self.bp_view_background.setObjectName("bp_view_background")
        self.gridLayout.addWidget(self.bp_view_background, 3, 1, 1, 1)
        self.cb_enabled = QtWidgets.QCheckBox(self.groupBox)
        self.cb_enabled.setChecked(True)
        self.cb_enabled.setTristate(False)
        self.cb_enabled.setObjectName("cb_enabled")
        self.gridLayout.addWidget(self.cb_enabled, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(BkgToolsWidget)
        QtCore.QMetaObject.connectSlotsByName(BkgToolsWidget)

    def retranslateUi(self, BkgToolsWidget):
        _translate = QtCore.QCoreApplication.translate
        BkgToolsWidget.setWindowTitle(_translate("BkgToolsWidget", "Form"))
        self.groupBox.setTitle(_translate("BkgToolsWidget", "Background tools"))
        self.le_correction_factor.setText(_translate("BkgToolsWidget", "1.0"))
        self.pb_set_factor.setText(_translate("BkgToolsWidget", "Set Correction Factor"))
        self.pb_set_sigma.setText(_translate("BkgToolsWidget", "Set Gaussian Blurr Sigma"))
        self.le_gauss_sigma.setText(_translate("BkgToolsWidget", "0.0"))
        self.bp_view_background.setText(_translate("BkgToolsWidget", "View resulting background"))
        self.cb_enabled.setText(_translate("BkgToolsWidget", "Enable for Fit and P. Creator"))
